import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthProvider } from "@/lib/auth";
import { setSession } from "@/data/authRepository";
import { getVendorById, saveVendor } from "@/data/businessRepository";
import OrdersPage from "@/features/vendor/restaurant/orders/OrdersPage";
import StoreSettingsPage from "@/features/vendor/common/storefronts/StoreSettingsPage";
import AdminBusinessDetailPage from "@/features/admin/businesses/AdminBusinessDetailPage";
import { RequireCapability } from "@/lib/rbac";
import { RequireAuth } from "@/app/routes/routeGuards";
import { createOrder, getOrders } from "@/data/orderRepository";
import { TextEncoder } from "util";
import LegacyPOSRoute from "@/features/vendor/common/pos/LegacyPOSRoute";

global.TextEncoder = TextEncoder;

let container;
let root;
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const storefront = { id: "sf1", slug: "cafe", name: "Cafe", businessType: "restaurant", items: [{ id: "tea", name: "Tea", price: 100, available: true }], checkoutFields: {} };
const vendor = { id: "v1", email: "v@test", password: "x", name: "Cafe", slug: "cafe", businessType: "restaurant", onboarded: true, storefronts: [storefront], employees: [], capabilities: { insights: true, stores: false, team: false, tableOrdering: true }, features: {}, orderMode: "both", tables: [{ id: "t1", storefrontId: "sf1", number: 1, label: "Table 1" }] };
const render = async (element) => { container = document.createElement("div"); document.body.appendChild(container); root = createRoot(container); await act(async () => root.render(element)); await act(async () => {}); };
const click = async (element) => act(async () => element.dispatchEvent(new MouseEvent("click", { bubbles: true })));
const change = async (element, value) => act(async () => { element.value = value; element.dispatchEvent(new Event("change", { bubbles: true })); });
beforeEach(() => { localStorage.clear(); localStorage.setItem("vyapar360.seed_done", "true"); saveVendor(vendor); setSession({ vendorId: "v1", role: "owner" }); });
afterEach(async () => { if (root) await act(async () => root.unmount()); container?.remove(); root = null; });
const withAuth = (child, path = "/") => <MemoryRouter initialEntries={[path]}><AuthProvider><RequireAuth>{child}</RequireAuth></AuthProvider></MemoryRouter>;

test("Orders exposes conditional Tables tab and storefront-scoped derived state", async () => { await render(withAuth(<OrdersPage />)); expect(container.querySelector('[data-testid="tables-tab"]')).not.toBeNull(); await click(container.querySelector('[data-testid="tables-tab"]')); expect(container.querySelectorAll('[data-testid^="table-card-"]')).toHaveLength(1); expect(container.textContent).toContain("free"); });
test("Orders hides Tables when effective table capability is disabled", async () => { saveVendor({ ...vendor, capabilities: { ...vendor.capabilities, tableOrdering: false }, orderMode: "table" }); await render(withAuth(<OrdersPage />)); expect(container.querySelector('[data-testid="tables-tab"]')).toBeNull(); });
test("Store settings coerces disabled table capability to Counter and disables impossible modes", async () => { saveVendor({ ...vendor, capabilities: { ...vendor.capabilities, tableOrdering: false }, orderMode: "table" }); await render(withAuth(<StoreSettingsPage />)); expect(container.querySelector('[data-testid="order-mode-counter"]').checked).toBe(true); expect(container.querySelector('[data-testid="order-mode-table"]').disabled).toBe(true); expect(container.textContent).toContain("require the Platform Admin"); });
test("effective capability guard allows owner only when enabled", async () => { await render(withAuth(<Routes><Route path="/" element={<RequireCapability capability="insights" permission="viewInsights"><div data-testid="allowed">Allowed</div></RequireCapability>} /><Route path="/dashboard" element={<div data-testid="denied">Denied</div>} /></Routes>)); expect(container.querySelector('[data-testid="allowed"]')).not.toBeNull(); });
test("effective capability guard redirects disabled direct access", async () => { saveVendor({ ...vendor, capabilities: { ...vendor.capabilities, insights: false } }); await render(withAuth(<Routes><Route path="/" element={<RequireCapability capability="insights" permission="viewInsights"><div data-testid="allowed">Allowed</div></RequireCapability>} /><Route path="/dashboard" element={<div data-testid="denied">Denied</div>} /></Routes>)); expect(container.querySelector('[data-testid="denied"]')).not.toBeNull(); });
test("admin first toggle disables an effective legacy default and persists", async () => { const legacy = { ...vendor }; delete legacy.capabilities; saveVendor(legacy); await render(<MemoryRouter initialEntries={["/admin/businesses/v1"]}><Routes><Route path="/admin/businesses/:vendorId" element={<AdminBusinessDetailPage />} /><Route path="/admin/businesses" element={<div />} /></Routes></MemoryRouter>); const control = container.querySelector('[data-testid="admin-capability-insights"]'); expect(control.getAttribute("aria-checked")).toBe("true"); await click(control); expect(getVendorById("v1").capabilities.insights).toBe(false); });

test("Orders valid status action persists and updates the open detail", async () => { const order = createOrder({ vendorId: "v1", storefrontId: "sf1", source: "counter", items: [{ id: "tea", name: "Tea", price: 100, qty: 1 }] }); await render(withAuth(<OrdersPage />)); await click(container.querySelector(`[data-testid="view-order-${order.id}"]`)); expect(container.querySelector('[data-testid="change-status-preparing"]')).not.toBeNull(); await click(container.querySelector('[data-testid="change-status-preparing"]')); expect(getOrders("v1")[0].status).toBe("preparing"); expect(container.textContent).toContain("Preparing"); expect(container.querySelector('[data-testid="change-status-ready"]')).not.toBeNull(); });
test("table Add items mutates the existing order and totals without creating another", async () => { const order = createOrder({ vendorId: "v1", storefrontId: "sf1", source: "table", tableId: "t1", items: [{ id: "base", name: "Base", price: 50, qty: 1 }] }); await render(withAuth(<OrdersPage />)); await click(container.querySelector(`[data-testid="view-order-${order.id}"]`)); await change(container.querySelector('[data-testid="add-order-item-select"]'), "tea"); await click(container.querySelector('[data-testid="add-order-item-button"]')); const persisted = getOrders("v1"); expect(persisted).toHaveLength(1); expect(persisted[0].items.map(({ id }) => id)).toEqual(["base", "tea"]); expect(persisted[0].total).toBe(158); expect(container.textContent).toContain("Tea"); expect(order.id).toBe(persisted[0].id); });
test("table cancellation becomes Ready to close and explicit turnover becomes Free", async () => { window.confirm = jest.fn(() => true); const order = createOrder({ vendorId: "v1", storefrontId: "sf1", source: "table", tableId: "t1", items: [] }); await render(withAuth(<OrdersPage />)); await click(container.querySelector(`[data-testid="view-order-${order.id}"]`)); await click(container.querySelector('[data-testid="cancel-order-button"]')); expect(getOrders("v1")[0].status).toBe("cancelled"); expect(container.querySelector('[data-testid="complete-table-button"]')).not.toBeNull(); await click(container.querySelector('[data-testid="complete-table-button"]')); expect(getOrders("v1")[0].tableClosedAt).toBeTruthy(); });
test("table QR preview exposes exact context and triggers PNG download and print", async () => { const anchorClick = jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {}); const popup = { document: { write: jest.fn(), close: jest.fn() }, print: jest.fn() }; window.open = jest.fn(() => popup); await render(withAuth(<OrdersPage />)); await click(container.querySelector('[data-testid="tables-tab"]')); await click(container.querySelector('[data-testid="table-qr-t1"]')); await act(async () => { await new Promise((resolve) => setTimeout(resolve, 25)); }); expect(container.querySelector('[data-testid="table-qr-preview"]').textContent).toContain("Cafe"); expect(container.textContent).toContain("Table 1"); expect(container.textContent).toContain("/store/cafe?table=t1"); await click(container.querySelector('[data-testid="table-qr-download"]')); expect(anchorClick).toHaveBeenCalled(); await click(container.querySelector('[data-testid="table-qr-print"]')); expect(popup.document.write.mock.calls[0][0]).toContain("Table 1"); expect(popup.document.write.mock.calls[0][0]).toContain("?table=t1"); expect(popup.print).toHaveBeenCalled(); anchorClick.mockRestore(); });
test("general Store settings QR stays table-free and supports PNG download and print", async () => { const anchorClick = jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {}); const popup = { document: { write: jest.fn(), close: jest.fn() }, print: jest.fn() }; window.open = jest.fn(() => popup); await render(withAuth(<StoreSettingsPage />)); await act(async () => { await new Promise((resolve) => setTimeout(resolve, 25)); }); expect(container.querySelector('[data-testid="general-store-qr"]').textContent).toContain("/store/cafe"); expect(container.querySelector('[data-testid="general-store-qr"]').textContent).not.toContain("?table="); await click(container.querySelector('[data-testid="general-qr-download"]')); expect(anchorClick).toHaveBeenCalled(); await click(container.querySelector('[data-testid="general-qr-print"]')); expect(popup.document.write.mock.calls[0][0]).toContain("Cafe"); expect(popup.document.write.mock.calls[0][0]).toContain("/store/cafe"); expect(popup.document.write.mock.calls[0][0]).not.toContain("?table="); anchorClick.mockRestore(); });
test("legacy restaurant POS route redirects to Orders New", async () => { await render(withAuth(<Routes><Route path="/dashboard/pos" element={<LegacyPOSRoute />} /><Route path="/dashboard/orders/new" element={<div data-testid="restaurant-new-order">New</div>} /></Routes>, "/dashboard/pos")); expect(container.querySelector('[data-testid="restaurant-new-order"]')).not.toBeNull(); });
test("legacy salon POS route still renders salon POS", async () => { const salon = { ...vendor, businessType: "salon", orderMode: "counter", capabilities: { ...vendor.capabilities, tableOrdering: false }, storefronts: [{ id: "salon-sf", name: "Salon", businessType: "salon", services: [{ id: "cut", name: "Cut", price: 200, duration: 30, available: true }] }] }; saveVendor(salon); await render(withAuth(<Routes><Route path="/dashboard/pos" element={<LegacyPOSRoute />} /></Routes>, "/dashboard/pos")); expect(container.querySelector('[data-testid="pos-title"]').textContent).toContain("New booking"); expect(container.querySelector('[data-testid="salon-pos"]')).not.toBeNull(); });
