import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import CheckoutPage from "./CheckoutPage";
import { saveVendor } from "@/data/businessRepository";
import { getOrders } from "@/data/orderRepository";

let container; let root;
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const store = { id: "sf1", slug: "cafe", name: "Cafe", businessType: "restaurant", checkoutFields: {}, items: [{ id: "tea", name: "Tea", price: 100 }] };
const vendor = { id: "v1", email: "v@test", name: "Cafe", slug: "cafe", businessType: "restaurant", onboarded: true, employees: [], storefronts: [store], capabilities: { tableOrdering: true }, orderMode: "both", tables: [{ id: "t1", storefrontId: "sf1", label: "Table 1" }] };
const renderAt = async (url) => { window.history.pushState({}, "", url); container = document.createElement("div"); document.body.appendChild(container); root = createRoot(container); await act(async () => root.render(<MemoryRouter initialEntries={[url]}><Routes><Route path="/store/:slug/checkout" element={<CheckoutPage />} /><Route path="/store/:slug/order/:orderId" element={<div data-testid="done" />} /></Routes></MemoryRouter>)); await act(async () => {}); };
const click = async (element) => act(async () => element.dispatchEvent(new MouseEvent("click", { bubbles: true })));
const input = async (element, value) => act(async () => { const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set; setter.call(element, value); element.dispatchEvent(new Event("input", { bubbles: true })); });
beforeEach(() => { localStorage.clear(); localStorage.setItem("vyapar360.seed_done", "true"); saveVendor(vendor); jest.useFakeTimers(); });
afterEach(async () => { if (root) await act(async () => root.unmount()); container?.remove(); root = null; jest.useRealTimers(); });

test("valid table context survives cart, checkout, and persisted order", async () => { localStorage.setItem("vyapar360.cart.cafe.t1", JSON.stringify([{ id: "tea", name: "Tea", price: 100, qty: 1 }])); await renderAt("/store/cafe/checkout?table=t1"); expect(container.querySelector('[data-testid="checkout-table-context"]').textContent).toContain("Table 1"); await input(container.querySelector('[data-testid="checkout-name-input"]'), "Guest"); await click(container.querySelector('[data-testid="place-order-btn"]')); await act(async () => jest.runAllTimers()); expect(getOrders("v1")[0]).toMatchObject({ source: "table", tableId: "t1", storefrontId: "sf1" }); });
test("Both mode requires explicit recovery and persists a counter order", async () => { localStorage.setItem("vyapar360.cart.cafe.foreign", JSON.stringify([{ id: "tea", name: "Tea", price: 100, qty: 1 }])); await renderAt("/store/cafe/checkout?table=foreign"); expect(container.textContent).toContain("no longer valid"); await click(container.querySelector('[data-testid="continue-without-table"]')); await input(container.querySelector('[data-testid="checkout-name-input"]'), "Guest"); await click(container.querySelector('[data-testid="place-order-btn"]')); await act(async () => jest.runAllTimers()); expect(getOrders("v1")[0]).toMatchObject({ source: "counter", tableId: null }); });
test("Table-only mode blocks invalid table checkout without silent binding", async () => { saveVendor({ ...vendor, orderMode: "table" }); localStorage.setItem("vyapar360.cart.cafe.removed", JSON.stringify([{ id: "tea", name: "Tea", price: 100, qty: 1 }])); await renderAt("/store/cafe/checkout?table=removed"); expect(container.querySelector('[data-testid="continue-without-table"]')).toBeNull(); await click(container.querySelector('[data-testid="place-order-btn"]')); expect(getOrders("v1")).toHaveLength(0); expect(container.textContent).toContain("ask staff"); });
test("table carts are isolated and legacy table-free cart remains readable", async () => { localStorage.setItem("vyapar360.cart.cafe.t1", JSON.stringify([{ id: "tea", name: "Table tea", price: 100, qty: 1 }])); localStorage.setItem("vyapar360.cart.cafe.counter", JSON.stringify([{ id: "tea", name: "Counter tea", price: 100, qty: 2 }])); localStorage.setItem("vyapar360.cart.cafe", JSON.stringify([{ id: "tea", name: "Legacy tea", price: 100, qty: 3 }])); await renderAt("/store/cafe/checkout?table=t1"); expect(container.textContent).toContain("Table tea"); expect(container.textContent).not.toContain("Counter tea"); });
